project:
  title: "cpsc-course-counts"

quarto-required: ">=1.4"

format:
  html:
    toc: true
    highlight-style: ayu
    theme:
      light: flatly
      dark:  darkly
    code-link: true
    citation-hover: true
    footnotes-hover: true
